# -*- coding: utf-8 -*-
"""deploy_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2zDD-S0ZYrQORvl-9naVmjsZJxt-2h4
"""

pip install Flask tensorflow

from flask import Flask, request, jsonify
import tensorflow as tf
from keras.models import load_model
from sklearn.preprocessing import LabelEncoder
import numpy as np
import json

app = Flask(__name__)

# Memuat model
model = load_model('model_2.h5')

# Preprocessing
label_encoders = {}  # Harus diisi dengan LabelEncoder yang telah dilatih
# Anda harus menyimpan LabelEncoder yang telah dilatih dan memuatnya di sini
# Contoh: label_encoders['Eligibility'] = load_saved_label_encoder('Eligibility.pkl')

def preprocess_input(input_data):
    # Preprocess input data
    # Anda perlu mengubah input_data sesuai dengan struktur data yang diperlukan oleh model Anda
    # Juga, terapkan LabelEncoder pada kolom yang relevan
    processed_data = {}
    for feature in input_data:
        if feature in label_encoders:
            le = label_encoders[feature]
            processed_data[feature] = le.transform([input_data[feature]])[0]
        else:
            processed_data[feature] = input_data[feature]
    return processed_data

@app.route('/predict', methods=['POST'])
def predict():
    # Mendapatkan data dari request
    data = request.get_json(force=True)

    # Memastikan data dalam format yang benar
    input_data = preprocess_input(data)

    # Melakukan prediksi
    prediction = model.predict(np.array([list(input_data.values())]))

    # Mengirimkan hasil prediksi
    return jsonify({'prediction': prediction.tolist()})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)