# -*- coding: utf-8 -*-
"""deploy_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c2zDD-S0ZYrQORvl-9naVmjsZJxt-2h4
"""

pip install Flask tensorflow

from flask import Flask, request, jsonify
import tensorflow as tf
from keras.models import load_model
from sklearn.preprocessing import LabelEncoder
import numpy as np
import json

app = Flask(__name__)


model = load_model('model_2.h5')


label_encoders = {}  


def preprocess_input(input_data):
    processed_data = {}
    for feature in input_data:
        if feature in label_encoders:
            le = label_encoders[feature]
            processed_data[feature] = le.transform([input_data[feature]])[0]
        else:
            processed_data[feature] = input_data[feature]
    return processed_data

@app.route('/predict', methods=['POST'])
def predict():
    data = request.get_json(force=True)
    input_data = preprocess_input(data)
    prediction = model.predict(np.array([list(input_data.values())]))

    return jsonify({'prediction': prediction.tolist()})

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)
